" This is standard pathogen and Vim setup
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

" File exploration
Bundle 'mileszs/ack.vim'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/nerdtree'

" Git integration
Bundle 'airblade/vim-gitgutter'
Bundle 'tpope/vim-fugitive'

" Coloring and syntax highlighting
Bundle 'altercation/vim-colors-solarized'
Bundle 'travitch/hasksyn'
Bundle 'kchmck/vim-coffee-script'
Bundle 'slim-template/vim-slim'
Bundle 'digitaltoad/vim-jade'
Bundle 'pbrisbin/html-template-syntax'

" Text manipulation
Bundle 'junegunn/vim-easy-align'
Bundle 'scrooloose/nerdcommenter'

" Vim Airline
Plugin 'bling/vim-airline'
let g:airline_powerline_fonts = 1

" Vim JavaScript Plugin
Plugin 'jelera/vim-javascript-syntax'

" Vim Snippets
Plugin 'SirVer/ultisnips'

" YCM
Plugin 'Valloric/YouCompleteMe'

filetype plugin indent on

syntax on

" File type extenstions
au BufRead,BufNewFile *.hamlc set ft=haml
au BufRead,BufNewFile *.thor set filetype=ruby
au BufRead,BufNewFile *.md set filetype=markdown

" UTF-8 everywhere
set encoding=utf-8
set fileencoding=utf-8

" Use 7.4 hybrid numbering
set relativenumber
set number

" Keep temp files in a central location
set backupdir=~/.vim/tmp,/var/tmp,/tmp
set directory=~/.vim/tmp,/var/tmp,/tmp

" Use width-2 soft tabs
set expandtab
set shiftwidth=2
set softtabstop=2
set smartindent

" Better search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Shell-style tab completion
set wildmenu
set wildmode=list:longest

" CtrlP .ignore
set wildignore+=*/cabal-dev/*,*/node_modules/*,*/bower_components/*,*.so,*.o,*.hi

" Use 256 color schemes
set t_Co=256
colorscheme ir_black

" Allow backspacing over auto-indents
set backspace=indent,eol,start

" Trailing whitespace tools
highlight ExtraWhitespace ctermbg=237 guibg=237
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Save on losing focus
au FocusLost * :wa

" GitGutter
highlight clear SignColumn
let g:gitgutter_sign_column_always = 1

" Open ggrep in a quickfix window
autocmd QuickFixCmdPost *grep* cwindow

" Tweaks
let mapleader=","

map <leader><leader> <c-^>

map <leader>b :NERDTreeToggle<cr>
map <leader>f :NERDTreeFocus<cr>
nnoremap <leader>ev <c-w><c-v><c-l>:e $MYVIMRC<cr>
map <leader>g :Ack
map <leader>x :wq<cr>
map <leader>s :w<cr>
map <leader>q :q<cr>
map <leader>p :set paste<cr>

map <leader><up> :CoqUndo<cr>
map <leader><left> :CoqToCursor<cr>
map <leader><down> :CoqNext<cr>

" Start interactive EasyAlign in visual mode
vmap <Enter> <Plug>(EasyAlign)

" Slightly faster paging
nnoremap <c-e> 5<c-e>
nnoremap <c-y> 5<c-y>

" Window navigation
map <Tab>J :split<cr><c-w>j
map <Tab>L :vsplit<cr><c-w>l

nnoremap <Tab>j <c-w>j
nnoremap <Tab>k <c-w>k
nnoremap <Tab>h <c-w>h
nnoremap <Tab>l <c-w>l
inoremap <Tab>j <esc><c-w>j
inoremap <Tab>k <esc><c-w>k
inoremap <Tab>h <esc><c-w>h
inoremap <Tab>l <esc><c-w>l

" Let's do this
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
inoremap jj <esc>

" Move line-wise on wrapped lines
nnoremap j gj
nnoremap k gk

" Indent
vnoremap < <gv
vnoremap > >gv

" Remove Highlight after Search
nnoremap <esc> :noh<return><esc>


" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-b>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
