# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="tim"

# Aliases
alias e='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias ew='/usr/local/bin/wstorm'
alias zshconfig="vi ~/.zshrc"
alias ohmyzsh="vi ~/.oh-my-zsh"
alias c='clear'
alias tmk='tmux kill-session -t Tim'
alias do_personal='ssh root@104.131.24.10'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias gpull="git pull origin"
alias ga="git add ."
alias gs="git status"
alias gr="git remote -v"
alias gb="git checkout -b"
alias gba="git branch --all"
alias gch="git checkout"
alias gm="git merge"

# GHI Commands
alias assign_issue="sh ~/Shell\ Scripts/tiy-assignment.sh"


# Disable weekly update checks
DISABLE_AUTO_UPDATE="true"

# Disable auto-setting of terminal title
DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? Plugins can be found in:
#   ~/.oh-my-zsh/plugins/*
#
# Custom plugins may be added to:
#   ~/.oh-my-zsh/custom/plugins/
#
# Example format:
#   plugins=(rails git textmate ruby)
plugins=()

source $ZSH/oh-my-zsh.sh

export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH
export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"

# Disable auto-correct
unsetopt correct_all

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# Customize to your needs...
ZSH_THEME_GIT_PROMPT_PREFIX=" on %{$fg[magenta]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[green]%}!"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[green]%}?"
ZSH_THEME_GIT_PROMPT_CLEAN=""

# Always work in a tmux session if tmux is installed
#if which tmux 2>&1 >/dev/null; then
  #if [ $TERM != "screen-256color" ] && [  $TERM != "screen" ]; then
    #tmux attach -t hack || tmux new -s hack; exit
  #fi
#fi

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
