export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="/usr/local/bin:$PATH"

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="chris"

# Aliases
alias zshconfig="subl ~/.zshrc"
alias ohmyzsh="subl ~/.oh-my-zsh"
alias e='subl .'
alias c='clear'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit -am"
alias gpull="git pull origin"
alias ga="git add ."
alias gs="git status"
alias gr="git remove -v"
alias gb="git checkout -b"
alias gba="git branch --all"

# GHI Commands
alias assign_issue="sh ~/Shell\ Scripts/tiy-assignment.sh"


# Disable weekly update checks
DISABLE_AUTO_UPDATE="true"

# Disable auto-setting of terminal title
DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? Plugins can be found in:
#   ~/.oh-my-zsh/plugins/*
#
# Custom plugins may be added to:
#   ~/.oh-my-zsh/custom/plugins/
#
# Example format:
#   plugins=(rails git textmate ruby)
plugins=(git rbenv)

source $ZSH/oh-my-zsh.sh

# Disable auto-correct
unsetopt correct_all

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# Customize to your needs...
# export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/git/bin:/opt/local/bin
ZSH_THEME_GIT_PROMPT_PREFIX=" on %{$fg[magenta]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[green]%}!"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[green]%}?"
ZSH_THEME_GIT_PROMPT_CLEAN=""

# Always work in a tmux session if tmux is installed
#if which tmux 2>&1 >/dev/null; then
  #if [ $TERM != "screen-256color" ] && [  $TERM != "screen" ]; then
    #tmux attach -t hack || tmux new -s hack; exit
  #fi
#fi
